### ISSUE TITLE
Add at least one test

### ISSUE THREAD

**Issue by beleran** [dhorelik/crew-management#1]

**Comment by dhorelik** [comment]
done - https://github.com/dhorelik/crew-management/blob/master/src/components/Board/component.test.js

**Comment by beleran** [comment]
npm test fails with 
 FAIL  src/components/Board/component.test.js
  ● Test suite failed to run

    TypeError: environment.teardown is not a function

**Comment by dhorelik** [comment]
ok, it used to work locally, but I believe I've found why it could be failing. It's basically a version conflict which occurs for jest v23. I had to explicitly install it so that `flow-typed` could generate library definitions for it and mute flow errors. Now that I've undone it, flow still shows no errors and the tests should be fine. Added a note on this to the ReadMe.

**Comment by beleran** [comment]
Test is fixed. Thank you
